version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fdDAg1r9wEa9qxJi2hoy/4JzYQ0zDt4aXQoEhFjmCUo"
      - checkout
      - restore_cache:
          keys:
            - dependencies-
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-
          paths:
              - node_modules
      - run:
          name: Gatsby build site
          command: npm run build
      - run:
          name: Prepare shell commands
          command: cp ./scripts/gatsby-deploy.sh ../ && chmod +x ../gatsby-deploy.sh
      - run:
          name: Run deploy scripts
          command: ../gatsby-deploy.sh